import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

import DeckGL from '@deck.gl/react';
import {MapView} from '@deck.gl/core';
import {TileLayer} from '@deck.gl/geo-layers';
import {BitmapLayer, PathLayer} from '@deck.gl/layers';
import { WebMercatorViewport } from '@deck.gl/core';
import { TextLayer } from '@deck.gl/layers';

const INITIAL_VIEW_STATE = {
  latitude: -80,
  longitude: 0,
  zoom: 2,
  maxZoom: 10,
  minZoom: 1,
  // maxPitch: 89,
  bearing: 0
};
const viewport = new WebMercatorViewport({
  width: 12288,
  height: 12288,
  longitude: -35,
  latitude:45,
  zoom: 3,
  maxZoom: 8,
  pitch: 0,
  bearing: 0
});
const newViewport = viewport.fitBounds([
  [0, 0], [-66.5, 90]
]);
/* global window */
const devicePixelRatio = (typeof window !== 'undefined' && window.devicePixelRatio) || 1;

function getTooltip({tile}) {
  return tile && `tile: x: ${tile.x}, y: ${tile.y}, z: ${tile.z}`;
}

export default function Home({showBorder = true, onTilesLoad = null}) {
  const tileLayer = new TileLayer({
    // https://wiki.openstreetmap.org/wiki/Slippy_map_tilenames#Tile_servers
    data: [
      `https://assets.yuanshen.site/tiles_dq/{z}/ppp{x}_{y}.jpg`
    ],

    // Since these OSM tiles support HTTP/2, we can make many concurrent requests
    // and we aren't limited by the browser to a certain number per domain.
    maxRequests: -1,

    pickable: false,
    onViewportLoad: onTilesLoad,
    autoHighlight: showBorder,
    highlightColor: [60, 60, 60, 40],
    // https://wiki.openstreetmap.org/wiki/Zoom_levels
    maxZoom: 8,
    minZoom: 2,
    // tileSize: 256 / devicePixelRatio,
    tileSize: 256 / devicePixelRatio,
    extent:[0,0,-79.17,135],
    renderSubLayers: props => {
      const {
        bbox: {west, south, east, north}
      } = props.tile;

      return [
        new BitmapLayer(props, {
          data: null,
          image: props.data,
          bounds: [west, south, east, north]
        }),
        showBorder &&
          new PathLayer({
            id: `${props.id}-border`,
            visible: props.visible,
            data: [[[west, north], [west, south], [east, south], [east, north], [west, north]]],
            getPath: d => d,
            getColor: [255, 255, 255],
            widthMinPixels: 1
          }),
          new TextLayer({
            id: `${props.id}-border-text`,
            visible: props.visible,
            data: [{
              tiles: `id:${props.id}`,
              lonlat:`(${west.toFixed(2)},${north.toFixed(2)})`
            }],
            fontWeight:'bold',
            getPosition:[west, north],
            getColor: [255, 255, 255],
            getText: d => d.lonlat,
            getSize: 32,
            getTextAnchor: 'middle',
            getAlignmentBaseline: 'center'
          }),
          new TextLayer({
            id: `${props.id}-border-center-text`,
            visible: props.visible,
            data: [{
              info: `${props.id}\n(x: ${props.tile.x}, y: ${props.tile.y}, z: ${props.tile.z})`,
              lonlat:[west+(east-west)/2, north+(south-north)/2],
            }],
            fontWeight:'bold',
            getPosition:d => d.lonlat,
            getColor: [255, 255, 255],
            getText: d => d.info,
            getSize: 24,
            getTextAnchor: 'middle',
            getAlignmentBaseline: 'center'
          })
      ];
    }
  });
  return (
    // <div style={{width:"100vw", height:"100vh",background:"url('https://assets.yuanshen.site/images/bg/144cf86c91fc23674dfeb1b7e8caba77148f550828707161fcd475814d92667b.png') no-repeat center center fixed",backgroundSize:"cover"}}>
    //   <div style={{width:"100vw", height:"100vh",background:"url('https://assets.yuanshen.site/images/bg/6008ef84b4b2136e34b55acb5a80d3b0ec84604dbbf4c6b25e1d67aa96f0b880.png') no-repeat center center fixed",backgroundSize:"cover"}}>
      <DeckGL
      layers={[tileLayer]}
      views={[new MapView({repeat: true})]}
      // viewState={viewport}
      initialViewState={INITIAL_VIEW_STATE}
      controller={true}
      // getTooltip={getTooltip}
    />
      // </div>
    // </div>
  );
  // return (
  //   <div className={styles.container}>
  //     <Head>
  //       <title>Create Next App</title>
  //       <meta name="description" content="Generated by create next app" />
  //       <link rel="icon" href="/favicon.ico" />
  //     </Head>

  //     <main className={styles.main}>
  //       <h1 className={styles.title}>
  //         Welcome to <a href="https://nextjs.org">Next.js!</a>
  //       </h1>

  //       <p className={styles.description}>
  //         Get started by editing{' '}
  //         <code className={styles.code}>pages/index.js</code>
  //       </p>

  //       <div className={styles.grid}>
  //         <a href="https://nextjs.org/docs" className={styles.card}>
  //           <h2>Documentation &rarr;</h2>
  //           <p>Find in-depth information about Next.js features and API.</p>
  //         </a>

  //         <a href="https://nextjs.org/learn" className={styles.card}>
  //           <h2>Learn &rarr;</h2>
  //           <p>Learn about Next.js in an interactive course with quizzes!</p>
  //         </a>

  //         <a
  //           href="https://github.com/vercel/next.js/tree/master/examples"
  //           className={styles.card}
  //         >
  //           <h2>Examples &rarr;</h2>
  //           <p>Discover and deploy boilerplate example Next.js projects.</p>
  //         </a>

  //         <a
  //           href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
  //           className={styles.card}
  //         >
  //           <h2>Deploy &rarr;</h2>
  //           <p>
  //             Instantly deploy your Next.js site to a public URL with Vercel.
  //           </p>
  //         </a>
  //       </div>
  //     </main>

  //     <footer className={styles.footer}>
  //       <a
  //         href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
  //         target="_blank"
  //         rel="noopener noreferrer"
  //       >
  //         Powered by{' '}
  //         <span className={styles.logo}>
  //           <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
  //         </span>
  //       </a>
  //     </footer>
  //   </div>
  // )
}
