name: issue-daily

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  issue-close-stale:
    name: close stale issues
    runs-on: ubuntu-latest
    steps:
      - uses: actions-cool/issues-helper@v2.4.1
        with:
          actions: "close-issues"
          token: ${{ secrets.GITHUB_TOKEN }}
          labels: "need reproduction, stale"
          inactive-day: 3
