name: issue-labeled

on:
  issues:
    types: [labeled]

jobs:
  issue-label-stale:
    name: label stale issues
    runs-on: ubuntu-latest
    steps:
      - uses: actions-cool/issues-helper@v2.4.0
        with:
          actions: "check-inactive"
          token: ${{ secrets.GITHUB_TOKEN }}
          inactive-day: 7
          inactive-label: "stale"
          exclude-labels: "bug, documentation, enhancement, feature, help wanted"
          body: |
            Hello @${{ github.event.issue.user.login }}. This issue is marked as `stale` because it has not had recent activity. Issues marked with `stale` will be closed if they have no activity within 3 days.

  issue-invalid:
    name: close and lock invalid
    if: github.event.label.name == 'invalid'
    runs-on: ubuntu-latest
    steps:
      - uses: actions-cool/issues-helper@v2.4.0
        with:
          actions: "close-issue, lock-issue"
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          body: |
            Hello @${{ github.event.issue.user.login }}. This issue is marked as `invalid` and closed. Please follow the issue template.

  issue-need-reproduction:
    name: need reproduction
    if: github.event.label.name == 'need reproduction'
    runs-on: ubuntu-latest
    steps:
      - uses: actions-cool/issues-helper@v2.4.0
        with:
          actions: "create-comment"
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          body: |
            Hello @${{ github.event.issue.user.login }}. Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) using a GitHub repository or [codesandbox](https://codesandbox.io). Issues marked with `need reproduction` will be closed if they have no activity within 3 days.
